name = "caffeine"
version = "0.1.0"
license = "BSD"
author = ["Damian Rouson", "Harris Snyder"]
maintainer = "rouson@lbl.gov"
copyright = "2021 UC Regents"

[dependencies]
assert = {git = "https://github.com/sourceryinstitute/assert", tag = "1.3.0"}

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.2.1"}
