name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-11, ubuntu-latest]

    env:
      PREFIX: install

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install on Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="${PATH}:/home/linuxbrew/.linuxbrew/bin"
        ./install.sh --prefix=${PREFIX}

    - name: Install on macOS
      if: contains(matrix.os, 'macos')
      run: |
        ./install.sh --prefix=${PREFIX}

    - name: Run unit tests
      run: |
        export GASNET_PSHM_NODES=8
        ./build/run-fpm.sh test
